FROM ubuntu:22.10@sha256:4a260e959a8e5186f1915e46bfb7663165ebfe5a7dc3365c76f9e3fb8d3019e4
ARG DEBIAN_FRONTEND=noninteractive
#
RUN apt update \
&&  apt install -y wget \
#
&&  VERSION=2.18 \
&&  ARCH=amd64 \
#
&&  wget -O /tmp/pandoc.tar.gz "https://github.com/jgm/pandoc/releases/download/${VERSION}/pandoc-${VERSION}-linux-${ARCH}.tar.gz" \
&&  tar -xvzf /tmp/pandoc.tar.gz -C /tmp \
&&  mv /tmp/pandoc*/bin/pandoc /usr/local/bin/pandoc