FROM ubuntu:20.04@sha256:7c9c7fed23def3653a0da5bc9ecb651efe155ebd5802c7ba5d585edaa6c89496
ARG DEBIAN_FRONTEND=noninteractive
#
RUN apt update \
&&  apt install -y wget \
#
&&  version=2.17.1.1 \
&&  arch=amd64 \
#
&&  wget -O /tmp/pandoc.tar.gz "https://github.com/jgm/pandoc/releases/download/${version}/pandoc-${version}-linux-${arch}.tar.gz" \
&&  tar -xvzf /tmp/pandoc.tar.gz -C /tmp \
&&  mv /tmp/pandoc*/bin/pandoc /usr/local/bin/pandoc