FROM ubuntu:22.10@sha256:a9bb8163533a936c7f4463319a299ff15e35a24db77ba6838d56c14f03b9863b
ARG DEBIAN_FRONTEND=noninteractive
#
RUN apt update \
&&  apt install -y wget \
#
&&  VERSION=2.18 \
&&  ARCH=arm64 \
#
&&  wget -O /tmp/pandoc.tar.gz "https://github.com/jgm/pandoc/releases/download/${VERSION}/pandoc-${VERSION}-linux-${ARCH}.tar.gz" \
&&  tar -xvzf /tmp/pandoc.tar.gz -C /tmp \
&&  mv /tmp/pandoc*/bin/pandoc /usr/local/bin/pandoc